/* eslint-disable @typescript-eslint/no-unsafe-assignment */
export const images = {
  logo: require('../assets/images/logo.png'),
  avataEmpty: require('../assets/images/avataEmpty.png'),
  iconCamera: require('../assets/images/iconCamera.png'),
  noNetwork: require('../assets/images/noNetwork.png'),
  iconSplash: require('../assets/images/iconSplash.png'),
  bgLogin: require('../assets/images/Group 3.png'),
  bgRegister: require('../assets/images/Group 2.png'),
  iconPlus: require('../assets/images/plus.png'),
  iconMinus: require('../assets/images/minus.png'),
  iconVoucher: require('../assets/images/voucherItem.png'),
  iconCart: require('../assets/images/cart111.png'),
  iconCartBlack: require('../assets/images/cart-black.png'),
  iconSearch: require('../assets/images/search.png'),
  iconStar: require('../assets/images/star4.png'),
  iconRightArrow: require('../assets/images/right-arrow.png'),
  iconBack: require('../assets/images/back.png'),
  changepass: require('../assets/images/changepass.png'),
  user: require('../assets/images/user.png'),
  location: require('../assets/images/placeholder1.png'),
  history: require('../assets/images/history.png'),
  support: require('../assets/images/support.png'),
  signinGG: require('../assets/images/signGG.png'),
  cameraIconx2: require('../assets/images/iconCamera2x.png'),
  logoApp: require('../assets/images/logoApp.png'),
};
