export enum ROUTES {
  GUEST_NAVIGATION = 'GUEST_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
  LOADING_SCREEN = 'LOADING_SCREEN',
  MENU_NAVIGATION = "MENU_NAVIGATION"
}

export enum GUEST_NAVIGATION {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  CATEGORY = 'CATEGORY',
  PRODUCTLIST = 'PRODUCTLIST',
}

export enum APP_NAVIGATION {
  ROOT = 'ROOT',
  CATEGORY = 'CATEGORY',
  PRODUCTLIST = 'PRODUCTLIST',
}

export enum MENU_NAVIGATION {
  HOME = 'HOME',
  FAVORITE = 'FAVORITE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ACCOUNT = 'ACCOUNT',
}
