export enum ROUTES {
  GUEST_NAVIGATION = 'GUEST_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
  LOADING_SCREEN = 'LOADING_SCREEN',
  MENU_NAVIGATION = 'MENU_NAVIGATION',
}


export enum GUEST_NAVIGATION {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  CATEGORY = "CATEGORY",
  CART = 'CART',
  PAYDETAIL='PAYDETAIL',
}

export enum APP_NAVIGATION {
  ROOT = 'ROOT',
  CATEGORY = 'CATEGORY',
  ADDRESS='ADDRESS',
  DETAILSPRODUCT = 'DETAILSPRODUCT',
  CART = 'CART',
  PAYDETAIL='PAYDETAIL',
}

export enum MENU_NAVIGATION {
  HOME = 'HOME',
  FAVORITE = 'FAVORITE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ACCOUNT = 'ACCOUNT',
}
